// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"starland-account/configs"
	"starland-account/internal/biz"
	"starland-account/internal/data"
	"starland-account/internal/service"
	"starland-account/internal/service/account"
	"starland-account/internal/service/activity"
)

// Injectors from wire.go:

// initApp
func initApp(cfg *configs.Config) (*service.Service, error) {
	dataData := data.NewData(cfg)
	accountRepo := data.NewAccountRepo(cfg, dataData)
	accountUsecase := biz.NewAccountUsecase(accountRepo)
	accountService := account.NewAccountService(cfg, accountUsecase)
	activityRepo := data.NewActivityRepo(cfg, dataData)
	activityLogRepo := data.NewActivityLogRepo(cfg, dataData)
	activityUsecase := biz.NewActivityUsecase(activityRepo, activityLogRepo)
	activityService := activity.NewActivityService(cfg, activityUsecase, accountUsecase)
	serviceService := service.NewService(accountService, activityService)
	return serviceService, nil
}
